import type { Metadata } from "next";
import { Roboto_Slab } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/NavBar";

const inter = Roboto_Slab({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{ backgroundColor: "#E0E1DD", color: "#0D1B2A" }}
      >
        {" "}
        <NavBar />
        <div className="max-w-screen-xl px-2.5 md:px-20 mx-auto h-full select-none ">
          {children}
        </div>
      </body>
    </html>
  );
}
